import '@/styles/globals.css'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { SWRConfig } from 'swr'

const inter = Inter({ subsets: ['latin'] })

export const fetcher = async (url, arg) => {
    // wait for .5s to test loading state
    process.env.NEXT_PUBLIC_NODE_ENV_FE === "development"
        && await new Promise((res) => setTimeout(res, 500))

    let options = {
        method: arg?.method || 'GET',
        headers: {
            "Content-Type": "application/json",
        },
        credentials: "include",
    }

    if (arg?.body) {
        options = { ...options, body: arg.body }
    }

    const response = await fetch(url, options)

    if (!response.ok) {
        const error = new Error('An error occurred. Please try again later.')
        error.info = await response.json()
        error.status = response.status
        throw error
    }

    return response.json()
}

export default function MyApp({ Component, pageProps }) {
    return (
        <div id="page">
            <style jsx global>{`
        html {
          font-family: ${inter.style.fontFamily};
        }
      `}</style>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SWRConfig
                value={{
                    fetcher: fetcher,
                    revalidateOnFocus: false
                }}>
                <Component {...pageProps} />
            </SWRConfig>
        </div>
    )
}
