
import {
  IconAlertCircle,
  IconArrowDownRight,
  IconArrowForward,
  IconArrowNarrowRight,
  IconArrowRight,
  IconBookmark,
  IconCalendarEvent,
  IconCheck,
  IconChecklist,
  IconChefHat,
  IconChevronUp,
  IconChevronsUp,
  IconCircleMinus,
  IconCloudUpload,
  IconCross,
  IconDotsVertical,
  IconEqual,
  IconGridDots,
  IconGripVertical,
  IconLoader,
  IconMenuOrder,
  IconMinus,
  IconNotebook,
  IconPlus,
  IconShoppingCartPlus,
  IconShoppingList,
  IconTrash,
  IconVerticalEllipsis
} from '@/components/Icon'

import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import Button from '../components/Button2'

export default function Home() {
  const sectionClasses = "bg-white p-8 mb-8 [&>h2]:font-bold [&>h2]:mb-4"
  return (
    <>
      <Head>
        <title>Cookbook V2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-8'>
        <div className='w-full'>
          <section className={sectionClasses}>
            <h2>
              Unstyled Button:
            </h2>
            <div>
              <Button unstyled>Unstyled Button</Button>
            </div>
          </section>

          <section className={sectionClasses}>
            <h2>
              Label Styled Buttons:
            </h2>

            <div className='flex flex-wrap gap-4'>
              <Button primary>Edit</Button>
              <Button primary disabled>Primary Disabled</Button>
              <Button primary uppercase>primary</Button>
              <Button secondary uppercase>secondary</Button>
              <Button danger uppercase>danger</Button>
              <Button danger uppercase compact>compact</Button>
              <Button danger uppercase compact withLeftIcon={<IconTrash size={14} />}>compact & Left Icon</Button>
              <Button primary withLeftIcon={<IconTrash size={14} />}>With Left Icon</Button>
              <Button primary withRightIcon={<IconArrowRight size={14} />}>With Right Icon</Button>
              <Button secondary uppercase withRightIcon={<IconArrowRight size={14} />}>Secondary & R Icon</Button>
              <Button compact primary withRightIcon={<IconArrowRight size={14} />}>Compact & Right Icon</Button>
              <Button primary uppercase fullWidth>Button w-full</Button>
            </div>
          </section>

          <section className={sectionClasses}>
            <h2>
              Action Buttons:
            </h2>

            <div className='flex flex-wrap gap-4'>
              <Button compact primary withLeftIcon={<IconTrash size={14} />}></Button>
              <Button compact secondary withLeftIcon={<IconTrash size={14} />}></Button>
              <Button compact danger withLeftIcon={<IconTrash size={14} />}></Button>
              <Button primary withLeftIcon={<IconNotebook size={16} />}></Button>
              <Button secondary withLeftIcon={<IconCalendarEvent size={16} />}></Button>
              <Button danger withLeftIcon={<IconTrash size={16} />}></Button>

              <Button unstyled withLeftIcon={<IconGridDots size={16} />}></Button>
            </div>
          </section>
        </div>
      </main>
    </>
  )
}

/*         <div>
          <IconCircleMinus />
          <IconShoppingList />
          <IconAlertCircle />
          <IconArrowDownRight />
          <IconArrowRight />
          <IconArrowNarrowRight />
          <IconArrowForward />
          <IconBookmark />
          <IconCalendarEvent />
          <IconCheck />
          <IconCross />
          <IconChecklist />
          <IconChefHat />
          <IconChevronUp />
          <IconChevronsUp />
          <IconCloudUpload />
          <IconDotsVertical />
          <IconEqual />
          <IconGripVertical />
          <IconLoader />
          <IconMenuOrder />
          <IconMinus />
          <IconNotebook />
          <IconGridDots />
          <IconPlus />
          <IconShoppingCartPlus />
          <IconTrash />
          <IconVerticalEllipsis />
        </div> */

