import Alert from '@/components/Alert'
import Button from '@/components/Button'
import {
    IconArrowDownRight,
    IconArrowForward,
    IconBookmark,
    IconCalendarEvent,
    IconCheck,
    IconChecklist,
    IconChefHat,
    IconChevronUp,
    IconChevronsUp,
    IconCloudUpload,
    IconCross,
    IconDotsVertical,
    IconEqual,
    IconGripVertical,
    IconLoader,
    IconMenuOrder,
    IconMinus,
    IconNotebook,
    IconPlus,
    IconShoppingCartPlus,
    IconTrash,
    IconVerticalEllipsis
} from '@/components/Icon'

import IconGridDots from '@/components/Icon/icons/icon-grid-dots'

import Head from 'next/head'
import Link from 'next/link'



export default function Home() {

    return (
        <>
            <Head>
                <title>Cookbook V2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Link href="/new">Create recipe</Link>
                <hr />
                <hr />
                <div style={{ display: 'flex', alignItems: 'flex-start', flexFlow: 'row wrap', gap: '1rem', marginBlockEnd: '2rem' }}>
                    <Button appearance='danger' uppercase leftIcon={<IconGridDots size={16} />}>Cancel</Button>
                    <Button appearance='danger' variant='outline' rightIcon={<IconGridDots size={16} />}>Super Button</Button>
                    <Button appearance='danger' variant='light' leftIcon={<IconGridDots size={16} />} rightIcon={<IconGridDots size={16} />}>Button</Button>

                    <Button leftIcon={<IconCheck size={16} />}>Button</Button>
                    <Button rightIcon={<IconCheck size={16} />} variant="outline">Button</Button>
                    <Button leftIcon={<IconCheck size={16} />} variant='light' rightIcon={<IconCheck size={16} />}>Button</Button>

                    <Button appearance='secondary' compact leftIcon={<IconCheck size={16} />}>Button</Button>
                    <Button appearance='secondary' rightIcon={<IconCheck size={16} />} variant="outline">Button</Button>
                    <Button appearance='secondary' leftIcon={<IconCheck size={16} />} variant='light' rightIcon={<IconCheck size={16} />}>Button</Button>
                </div>
                <hr />
                <hr />
                <Alert appearance="danger" title="Error">
                    This is danger, I am danger. <a href='/'>Follow the rabbit.</a>
                </Alert>
                <Alert appearance="danger" title="Error" variant="outline">Hakuna Matata</Alert>
                <Alert appearance="danger" title="Error" variant="light" removable>Hey!</Alert>

                <Alert appearance="success" title="Success" removable>This is success, I am success.</Alert>
                <Alert appearance="success" title="Success" variant="outline">Hakuna Matata</Alert>
                <Alert appearance="success" title="Success" variant="light">Hey!</Alert>

                <Alert appearance="info" title="Info">This is info, I am Info.</Alert>
                <Alert appearance="info" title="Info" variant="outline" removable>Hakuna Matata</Alert>
                <Alert appearance="info" title="Info" variant="light">Hey!</Alert>

                <hr />
                <hr />
                <div>
                    <IconArrowDownRight />
                    <IconArrowForward />
                    <IconBookmark />
                    <IconCalendarEvent />
                    <IconCheck />
                    <IconCross />
                    <IconChecklist />
                    <IconChefHat />
                    <IconChevronUp />
                    <IconChevronsUp />
                    <IconCloudUpload />
                    <IconDotsVertical />
                    <IconEqual />
                    <IconGripVertical />
                    <IconLoader />
                    <IconMenuOrder />
                    <IconMinus />
                    <IconNotebook />
                    <IconPlus />
                    <IconShoppingCartPlus />
                    <IconTrash />
                    <IconVerticalEllipsis />
                </div>
            </main>
        </>
    )
}
